var promanControllers = angular.module('inspinia');
function pro_item_param_fp($scope, $location, $rootScope, $modal, $timeout, BasemanService, notify, $state, localeStorageService, FormValidatorService) {
    //设置当前对象名及主键名
    $scope.objconf = {
        classid: "pro_item_param_fp",
        key: "id",
        classids: "pro_item_param_fps",
        hasStats:false,
        //SqlWhere:"1=1", 该条不存在就不要赋值
    }
    //继承基类方法
    pro_item_param_fp = HczyCommon.extend(pro_item_param_fp, ctrl_view_public);
    pro_item_param_fp.__super__.constructor.apply(this, [$rootScope, $scope, $location, $modal,
        $timeout, BasemanService, notify, $state, localeStorageService, FormValidatorService]);

    $scope.viewColumns = [
        {
            id: "id",
            name: "#",
            field: "id",
            behavior: "select",
            cssClass: "cell-selection",
            width: 40,
            cannotTriggerInsert: true,
            resizable: false,
            selectable: false,
            focusable: false
        }, {
            id: "系列",
            name: "系列",
            field: "系列",
            width: 60,
            editor: Slick.Editors.ReadonlyText,
            formatter: Slick.Formatters.SelectOption,
        }, {
            id: "产品型号",
            name: "产品型号",
            field: "产品型号",
            width: 130,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "高档风量",
            name: "高档风量",
            field: "高档风量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "中档风量",
            name: "中档风量",
            field: "中档风量",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "低档风量",
            name: "低档风量",
            field: "低档风量",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "高档制冷量",
            name: "高档制冷量",
            field: "高档制冷量",
            width: 130,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "中档制冷量",
            name: "中档制冷量",
            field: "中档制冷量",
            width: 80,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "低档制冷量",
            name: "低档制冷量",
            field: "低档制冷量",
            width: 80,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "高档制热量",
            name: "高档制热量",
            field: "高档制热量",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "中档制热量",
            name: "中档制热量",
            field: "中档制热量",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "低档制热量",
            name: "低档制热量",
            field: "低档制热量",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "静压",
            name: "静压",
            field: "静压",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "噪声",
            name: "噪声",
            field: "噪声",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "风叶形式",
            name: "风叶形式",
            field: "风叶形式",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "风叶数量",
            name: "风叶数量",
            field: "风叶数量",
            width: 80,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "盘管形式",
            name: "盘管形式",
            field: "盘管形式",
            width: 80,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "电机形式",
            name: "电机形式",
            field: "电机形式",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "电机台数",
            name: "电机台数",
            field: "电机台数",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "输入功率",
            name: "输入功率",
            field: "输入功率",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "频率",
            name: "频率",
            field: "频率",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "供水量",
            name: "供水量",
            field: "供水量",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "水阻力",
            name: "水阻力",
            field: "水阻力",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "工作压力",
            name: "工作压力",
            field: "工作压力",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "风盘净重",
            name: "风盘净重",
            field: "风盘净重",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "风盘毛重",
            name: "风盘毛重",
            field: "风盘毛重",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "风盘净尺寸",
            name: "风盘净尺寸",
            field: "风盘净尺寸",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "风盘包装尺寸",
            name: "风盘包装尺寸",
            field: "风盘包装尺寸",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "进出水管",
            name: "进出水管",
            field: "进出水管",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "冷凝水管",
            name: "冷凝水管",
            field: "冷凝水管",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "生产许可证编号",
            name: "生产许可证编号",
            field: "生产许可证编号",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "机型代码",
            name: "机型代码",
            field: "机型代码",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "堆码层数",
            name: "堆码层数",
            field: "堆码层数",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "测试压力",
            name: "测试压力",
            field: "测试压力",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "产品执行标准",
            name: "产品执行标准",
            field: "产品执行标准",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "成品物料编码",
            name: "成品物料编码",
            field: "成品物料编码",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "进出水温度",
            name: "进出水温度",
            field: "进出水温度",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "左式右式",
            name: "左式右式",
            field: "左式右式",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "认证类型",
            name: "认证类型",
            field: "认证类型",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }];

    $scope.clearinformation = function () {
        $scope.data = {};
        $scope.data.currItem = {};
    };
    $scope.clearinformation();


    $scope.initData();

}

function pro_item_param_kq($scope, $location, $rootScope, $modal, $timeout, BasemanService, notify, $state, localeStorageService, FormValidatorService) {
    //设置当前对象名及主键名
    $scope.objconf = {
        classid: "pro_item_param_kq",
        key: "id",
        classids: "pro_item_param_kqs",
        sqlWhereBlockID:"sqlWhereBlock2",
        hasStats:false,
        //SqlWhere:"1=1", 该条不存在就不要赋值
    }
    //继承基类方法
    pro_item_param_kq = HczyCommon.extend(pro_item_param_kq, ctrl_view_public);
    pro_item_param_kq.__super__.constructor.apply(this, [$rootScope, $scope, $location, $modal,
        $timeout, BasemanService, notify, $state, localeStorageService, FormValidatorService]);

    $scope.viewColumns = [
        {
            id: "id",
            name: "#",
            field: "id",
            behavior: "select",
            cssClass: "cell-selection",
            width: 40,
            cannotTriggerInsert: true,
            resizable: false,
            selectable: false,
            focusable: false
        }, {
            id: "系列",
            name: "系列",
            field: "系列",
            width: 60,
            editor: Slick.Editors.ReadonlyText,
            formatter: Slick.Formatters.SelectOption,
        }, {
            id: "产品型号",
            name: "产品型号",
            field: "产品型号",
            width: 130,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "额定风量",
            name: "额定风量",
            field: "额定风量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "额定冷量",
            name: "额定冷量",
            field: "额定冷量",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "额定热量",
            name: "额定热量",
            field: "额定热量",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "水流量",
            name: "水流量",
            field: "水流量",
            width: 130,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "水阻力",
            name: "水阻力",
            field: "水阻力",
            width: 80,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "机外余压",
            name: "机外余压",
            field: "机外余压",
            width: 80,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "噪声",
            name: "噪声",
            field: "噪声",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "风机形式",
            name: "风机形式",
            field: "风机形式",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "风机数量",
            name: "风机数量",
            field: "风机数量",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "电机形式",
            name: "电机形式",
            field: "电机形式",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "电机台数",
            name: "电机台数",
            field: "电机台数",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "输入功率",
            name: "输入功率",
            field: "输入功率",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "额定电流",
            name: "额定电流",
            field: "额定电流",
            width: 80,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "电源电压相数",
            name: "电源电压相数",
            field: "电源电压相数",
            width: 80,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "频率",
            name: "频率",
            field: "频率",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "供水量",
            name: "供水量",
            field: "供水量",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "水阻力2",
            name: "水阻力2",
            field: "水阻力2",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "净重量",
            name: "净重量",
            field: "净重量",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "外形尺寸",
            name: "外形尺寸",
            field: "外形尺寸",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "包装尺寸",
            name: "包装尺寸",
            field: "包装尺寸",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "堆码层数",
            name: "堆码层数",
            field: "堆码层数",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "进出水管",
            name: "进出水管",
            field: "进出水管",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "生产许可证编号",
            name: "生产许可证编号",
            field: "生产许可证编号",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "机型代码",
            name: "机型代码",
            field: "机型代码",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "成品物料编码",
            name: "成品物料编码",
            field: "成品物料编码",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }];

    $scope.clearinformation = function () {
        $scope.data = {};
        $scope.data.currItem = {};
    };
    $scope.clearinformation();


    $scope.initData();

}

function pro_item_param_sj($scope, $location, $rootScope, $modal, $timeout, BasemanService, notify, $state, localeStorageService, FormValidatorService) {
    //设置当前对象名及主键名
    $scope.objconf = {
        classid: "pro_item_param_sj",
        key: "id",
        classids: "pro_item_param_sjs",
        sqlWhereBlockID:"sqlWhereBlock3",
        hasStats:false,
        //SqlWhere:"1=1", 该条不存在就不要赋值
    }
    //继承基类方法
    pro_item_param_sj = HczyCommon.extend(pro_item_param_sj, ctrl_view_public);
    pro_item_param_sj.__super__.constructor.apply(this, [$rootScope, $scope, $location, $modal,
        $timeout, BasemanService, notify, $state, localeStorageService, FormValidatorService]);

    $scope.viewColumns = [
        {
            id: "id",
            name: "#",
            field: "id",
            behavior: "select",
            cssClass: "cell-selection",
            width: 40,
            cannotTriggerInsert: true,
            resizable: false,
            selectable: false,
            focusable: false
        }, {
            id: "系列",
            name: "系列",
            field: "系列",
            width: 60,
            editor: Slick.Editors.ReadonlyText,
            formatter: Slick.Formatters.SelectOption,
        }, {
            id: "产品型号1",
            name: "产品型号1",
            field: "产品型号1",
            width: 130,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "防水等级",
            name: "防水等级",
            field: "防水等级",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "防触电保护类别",
            name: "防触电保护类别",
            field: "防触电保护类别",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "额定电压频率",
            name: "额定电压频率",
            field: "额定电压频率",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷量",
            name: "制冷量",
            field: "制冷量",
            width: 130,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷量KCAL",
            name: "制冷量KCAL",
            field: "制冷量KCAL",
            width: 80,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制热量",
            name: "制热量",
            field: "制热量",
            width: 80,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制热量KCAL",
            name: "制热量KCAL",
            field: "制热量KCAL",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷额定电流",
            name: "制冷额定电流",
            field: "制冷额定电流",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制热额定电流",
            name: "制热额定电流",
            field: "制热额定电流",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "最大输入电流",
            name: "最大输入电流",
            field: "最大输入电流",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷额定消耗功率",
            name: "制冷额定消耗功率",
            field: "制冷额定消耗功率",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制热额定消耗功率",
            name: "制热额定消耗功率",
            field: "制热额定消耗功率",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "最恶劣工况下输入电流",
            name: "最恶劣工况下输入电流",
            field: "最恶劣工况下输入电流",
            width: 80,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "最恶劣工况下输入功率",
            name: "最恶劣工况下输入功率",
            field: "最恶劣工况下输入功率",
            width: 80,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "换热器侧最大工作压力",
            name: "换热器侧最大工作压力",
            field: "换热器侧最大工作压力",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "吸气侧最大工作压力",
            name: "吸气侧最大工作压力",
            field: "吸气侧最大工作压力",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "排气侧最大工作压力",
            name: "排气侧最大工作压力",
            field: "排气侧最大工作压力",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷剂名称",
            name: "制冷剂名称",
            field: "制冷剂名称",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷剂注入量",
            name: "制冷剂注入量",
            field: "制冷剂注入量",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷剂控制方式",
            name: "制冷剂控制方式",
            field: "制冷剂控制方式",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "噪声",
            name: "噪声",
            field: "噪声",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "压缩机形式",
            name: "压缩机形式",
            field: "压缩机形式",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "压缩机启动方式",
            name: "压缩机启动方式",
            field: "压缩机启动方式",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "压缩机数量",
            name: "压缩机数量",
            field: "压缩机数量",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "压缩机容量调节",
            name: "压缩机容量调节",
            field: "压缩机容量调节",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "风侧换热器形式",
            name: "风侧换热器形式",
            field: "风侧换热器形式",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "风侧换热器风机数量",
            name: "风侧换热器风机数量",
            field: "风侧换热器风机数量",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "风侧换热器额定功率",
            name: "风侧换热器额定功率",
            field: "风侧换热器额定功率",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "水侧换热器形式",
            name: "水侧换热器形式",
            field: "水侧换热器形式",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "水侧换热器水压降",
            name: "水侧换热器水压降",
            field: "水侧换热器水压降",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "水侧换热器制冷流量",
            name: "水侧换热器制冷流量",
            field: "水侧换热器制冷流量",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "水侧换热器机外扬程",
            name: "水侧换热器机外扬程",
            field: "水侧换热器机外扬程",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "水侧换热器水泵额定P",
            name: "水侧换热器水泵额定P",
            field: "水侧换热器水泵额定P",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "冷却水冷凝器类型",
            name: "冷却水冷凝器类型",
            field: "冷却水冷凝器类型",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "左式右式",
            name: "左式右式",
            field: "左式右式",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "冷却水冷凝器流量",
            name: "冷却水冷凝器流量",
            field: "冷却水冷凝器流量",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "冷却水冷凝器管径法兰",
            name: "冷却水冷凝器管径法兰",
            field: "冷却水冷凝器管径法兰",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "冷却水冷凝器水阻力",
            name: "冷却水冷凝器水阻力",
            field: "冷却水冷凝器水阻力",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "冷冻水蒸发器形式",
            name: "冷冻水蒸发器形式",
            field: "冷冻水蒸发器形式",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "冷冻水蒸发器管径法兰",
            name: "冷冻水蒸发器管径法兰",
            field: "冷冻水蒸发器管径法兰",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "冷冻水蒸发器水阻力",
            name: "冷冻水蒸发器水阻力",
            field: "冷冻水蒸发器水阻力",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "净重",
            name: "净重",
            field: "净重",
            width: 60,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "毛重",
            name: "毛重",
            field: "毛重",
            width: 60,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "外形尺寸",
            name: "外形尺寸",
            field: "外形尺寸",
            width: 60,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "包装尺寸",
            name: "包装尺寸",
            field: "包装尺寸",
            width: 60,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "叠放层数",
            name: "叠放层数",
            field: "叠放层数",
            width: 60,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "保护装置",
            name: "保护装置",
            field: "保护装置",
            width: 60,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "冷媒控制方式",
            name: "冷媒控制方式",
            field: "冷媒控制方式",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "进出水管尺寸",
            name: "进出水管尺寸",
            field: "进出水管尺寸",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "机组名称1",
            name: "机组名称1",
            field: "机组名称1",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "产品执行标准",
            name: "产品执行标准",
            field: "产品执行标准",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "是否需要能效认证",
            name: "是否需要能效认证",
            field: "是否需要能效认证",
            width: 60,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "能效比",
            name: "能效比",
            field: "能效比",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "能效执行标准",
            name: "能效执行标准",
            field: "能效执行标准",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "产品类型",
            name: "产品类型",
            field: "产品类型",
            width: 60,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "认证",
            name: "认证",
            field: "认证",
            width: 60,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "单冷热泵",
            name: "单冷热泵",
            field: "单冷热泵",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "机组分类",
            name: "机组分类",
            field: "机组分类",
            width: 60,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "成品物料编码",
            name: "成品物料编码",
            field: "成品物料编码",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "能效标识物料编码",
            name: "能效标识物料编码",
            field: "能效标识物料编码",
            width: 120,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "热回收量",
            name: "热回收量",
            field: "热回收量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "热回收水流量",
            name: "热回收水流量",
            field: "热回收水流量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "热回收形式",
            name: "热回收形式",
            field: "热回收形式",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "热回收水压降",
            name: "热回收水压降",
            field: "热回收水压降",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }];

    $scope.clearinformation = function () {
        $scope.data = {};
        $scope.data.currItem = {};
    };
    $scope.clearinformation();


    $scope.initData();

}

function pro_item_param_thj($scope, $location, $rootScope, $modal, $timeout, BasemanService, notify, $state, localeStorageService, FormValidatorService) {
    //设置当前对象名及主键名
    $scope.objconf = {
        classid: "pro_item_param_thj",
        key: "id",
        classids: "pro_item_param_thjs",
        sqlWhereBlockID:"sqlWhereBlock4",
        hasStats:false,
        //SqlWhere:"1=1", 该条不存在就不要赋值
    }
    //继承基类方法
    pro_item_param_thj = HczyCommon.extend(pro_item_param_thj, ctrl_view_public);
    pro_item_param_thj.__super__.constructor.apply(this, [$rootScope, $scope, $location, $modal,
        $timeout, BasemanService, notify, $state, localeStorageService, FormValidatorService]);

    $scope.viewColumns = [
        {
            id: "id",
            name: "#",
            field: "id",
            behavior: "select",
            cssClass: "cell-selection",
            width: 40,
            cannotTriggerInsert: true,
            resizable: false,
            selectable: false,
            focusable: false
        }, {
            id: "整机型号",
            name: "整机型号",
            field: "整机型号",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "产品型号",
            name: "产品型号",
            field: "产品型号",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "室内机组型号",
            name: "室内机组型号",
            field: "室内机组型号",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "匹配外机型号",
            name: "匹配外机型号",
            field: "匹配外机型号",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "额定电压数",
            name: "额定电压数",
            field: "额定电压数",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "频率",
            name: "频率",
            field: "频率",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷量",
            name: "制冷量",
            field: "制冷量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制热量",
            name: "制热量",
            field: "制热量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷额定电流",
            name: "制冷额定电流",
            field: "制冷额定电流",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制热额定电流",
            name: "制热额定电流",
            field: "制热额定电流",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷消耗功率",
            name: "制冷消耗功率",
            field: "制冷消耗功率",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制热消耗功率",
            name: "制热消耗功率",
            field: "制热消耗功率",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "最大电流",
            name: "最大电流",
            field: "最大电流",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "最大功率",
            name: "最大功率",
            field: "最大功率",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "换热器侧最大工作压力",
            name: "换热器侧最大工作压力",
            field: "换热器侧最大工作压力",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "吸气侧最大工作压力",
            name: "吸气侧最大工作压力",
            field: "吸气侧最大工作压力",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "排气侧最大工作压力",
            name: "排气侧最大工作压力",
            field: "排气侧最大工作压力",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷剂名称",
            name: "制冷剂名称",
            field: "制冷剂名称",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷剂注入量",
            name: "制冷剂注入量",
            field: "制冷剂注入量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "风量",
            name: "风量",
            field: "风量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "静压",
            name: "静压",
            field: "静压",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "内机噪声",
            name: "内机噪声",
            field: "内机噪声",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "外机噪声",
            name: "外机噪声",
            field: "外机噪声",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "内机净重",
            name: "内机净重",
            field: "内机净重",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "外机净重",
            name: "外机净重",
            field: "外机净重",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "内机毛重",
            name: "内机毛重",
            field: "内机毛重",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "外机毛重",
            name: "外机毛重",
            field: "外机毛重",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "内机机型代码",
            name: "内机机型代码",
            field: "内机机型代码",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "外机机型代码",
            name: "外机机型代码",
            field: "外机机型代码",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "电辅形式",
            name: "电辅形式",
            field: "电辅形式",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "电辅电压",
            name: "电辅电压",
            field: "电辅电压",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "电辅消耗功率",
            name: "电辅消耗功率",
            field: "电辅消耗功率",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "电辅电流",
            name: "电辅电流",
            field: "电辅电流",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "机组名称1",
            name: "机组名称1",
            field: "机组名称1",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "机组名称2",
            name: "机组名称2",
            field: "机组名称2",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "机组名称3",
            name: "机组名称3",
            field: "机组名称3",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "机组名称4",
            name: "机组名称4",
            field: "机组名称4",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "内机净尺寸",
            name: "内机净尺寸",
            field: "内机净尺寸",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "外机净尺寸",
            name: "外机净尺寸",
            field: "外机净尺寸",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "内机包装",
            name: "内机包装",
            field: "内机包装",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "外机包装",
            name: "外机包装",
            field: "外机包装",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "连接管液管规格",
            name: "连接管液管规格",
            field: "连接管液管规格",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "连接管气管规格",
            name: "连接管气管规格",
            field: "连接管气管规格",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "连接管最长配管规格",
            name: "连接管最长配管规格",
            field: "连接管最长配管规格",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "连接管追加冷媒量",
            name: "连接管追加冷媒量",
            field: "连接管追加冷媒量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "截止阀加大液管规格",
            name: "截止阀加大液管规格",
            field: "截止阀加大液管规格",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "截止阀加大气管规格",
            name: "截止阀加大气管规格",
            field: "截止阀加大气管规格",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "截止阀加大最长配管",
            name: "截止阀加大最长配管",
            field: "截止阀加大最长配管",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "截止阀加大追加冷媒量",
            name: "截止阀加大追加冷媒量",
            field: "截止阀加大追加冷媒量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "最大落差",
            name: "最大落差",
            field: "最大落差",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "连接方式",
            name: "连接方式",
            field: "连接方式",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "控制方式",
            name: "控制方式",
            field: "控制方式",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "凝水管管径",
            name: "凝水管管径",
            field: "凝水管管径",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "是否需要能效认证",
            name: "是否需要能效认证",
            field: "是否需要能效认证",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "能效比",
            name: "能效比",
            field: "能效比",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "能效执行标准",
            name: "能效执行标准",
            field: "能效执行标准",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "产品执行标准",
            name: "产品执行标准",
            field: "产品执行标准",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "产品类型",
            name: "产品类型",
            field: "产品类型",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "认证类型",
            name: "认证类型",
            field: "认证类型",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "单冷热泵",
            name: "单冷热泵",
            field: "单冷热泵",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "机组分类",
            name: "机组分类",
            field: "机组分类",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "面板风口的尺寸",
            name: "面板风口的尺寸",
            field: "面板风口的尺寸",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "成品内机物料编码",
            name: "成品内机物料编码",
            field: "成品内机物料编码",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "成品外机物料编码",
            name: "成品外机物料编码",
            field: "成品外机物料编码",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "室外机制冷电流",
            name: "室外机制冷电流",
            field: "室外机制冷电流",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "室外机制热电流",
            name: "室外机制热电流",
            field: "室外机制热电流",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "室外机制冷功率",
            name: "室外机制冷功率",
            field: "室外机制冷功率",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "室外机制热功率",
            name: "室外机制热功率",
            field: "室外机制热功率",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "室内机额定电压",
            name: "室内机额定电压",
            field: "室内机额定电压",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷量制热量单位",
            name: "制冷量制热量单位",
            field: "制冷量制热量单位",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "工况",
            name: "工况",
            field: "工况",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "定频变频",
            name: "定频变频",
            field: "定频变频",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "整机物料编码",
            name: "整机物料编码",
            field: "整机物料编码",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "内机包装2",
            name: "内机包装2",
            field: "内机包装2",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "外机包装2",
            name: "外机包装2",
            field: "外机包装2",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }]

    $scope.clearinformation = function () {
        $scope.data = {};
        $scope.data.currItem = {};
    };
    $scope.clearinformation();
    $scope.initData();
}

function pro_item_param_t($scope, $location, $rootScope, $modal, $timeout, BasemanService, notify, $state, localeStorageService, FormValidatorService) {
    //设置当前对象名及主键名
    $scope.objconf = {
        classid: "pro_item_param_t",
        key: "id",
        classids: "pro_item_param_ts",
        sqlWhereBlockID:"sqlWhereBlock5",
        hasStats:false,
        //SqlWhere:"1=1", 该条不存在就不要赋值
    }
    //继承基类方法
    pro_item_param_t = HczyCommon.extend(pro_item_param_t, ctrl_view_public);
    pro_item_param_t.__super__.constructor.apply(this, [$rootScope, $scope, $location, $modal,
        $timeout, BasemanService, notify, $state, localeStorageService, FormValidatorService]);

    $scope.viewColumns = [
        {
            id: "id",
            name: "#",
            field: "id",
            behavior: "select",
            cssClass: "cell-selection",
            width: 40,
            cannotTriggerInsert: true,
            resizable: false,
            selectable: false,
            focusable: false
        }, {
            id: "整机型号",
            name: "整机型号",
            field: "整机型号",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "产品型号",
            name: "产品型号",
            field: "产品型号",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "室内机组型号",
            name: "室内机组型号",
            field: "室内机组型号",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "匹配外机型号",
            name: "匹配外机型号",
            field: "匹配外机型号",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "额定电压相数",
            name: "额定电压相数",
            field: "额定电压相数",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "额定频率",
            name: "额定频率",
            field: "额定频率",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷量",
            name: "制冷量",
            field: "制冷量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制热量",
            name: "制热量",
            field: "制热量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷电流",
            name: "制冷电流",
            field: "制冷电流",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制热电流",
            name: "制热电流",
            field: "制热电流",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷消耗功率",
            name: "制冷消耗功率",
            field: "制冷消耗功率",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制热消耗功率",
            name: "制热消耗功率",
            field: "制热消耗功率",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "最大电流",
            name: "最大电流",
            field: "最大电流",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "最大功率",
            name: "最大功率",
            field: "最大功率",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "换热器侧MAX工作压力",
            name: "换热器侧MAX工作压力",
            field: "换热器侧MAX工作压力",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "吸气侧最大工作压力",
            name: "吸气侧最大工作压力",
            field: "吸气侧最大工作压力",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "排气侧最大工作压力",
            name: "排气侧最大工作压力",
            field: "排气侧最大工作压力",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷剂名称",
            name: "制冷剂名称",
            field: "制冷剂名称",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷剂注入量",
            name: "制冷剂注入量",
            field: "制冷剂注入量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "风量",
            name: "风量",
            field: "风量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "静压",
            name: "静压",
            field: "静压",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "内机噪声",
            name: "内机噪声",
            field: "内机噪声",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "外机噪声",
            name: "外机噪声",
            field: "外机噪声",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "内机净重",
            name: "内机净重",
            field: "内机净重",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "外机净重",
            name: "外机净重",
            field: "外机净重",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "内机毛重",
            name: "内机毛重",
            field: "内机毛重",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "外机毛重",
            name: "外机毛重",
            field: "外机毛重",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "内机机型代码",
            name: "内机机型代码",
            field: "内机机型代码",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "外机机型代码",
            name: "外机机型代码",
            field: "外机机型代码",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "电辅形式",
            name: "电辅形式",
            field: "电辅形式",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "电辅电压",
            name: "电辅电压",
            field: "电辅电压",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "电辅消耗功率",
            name: "电辅消耗功率",
            field: "电辅消耗功率",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "电辅电流",
            name: "电辅电流",
            field: "电辅电流",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "机组名称1",
            name: "机组名称1",
            field: "机组名称1",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "机组名称2",
            name: "机组名称2",
            field: "机组名称2",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "机组名称3",
            name: "机组名称3",
            field: "机组名称3",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "机组名称4",
            name: "机组名称4",
            field: "机组名称4",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "内机净尺寸",
            name: "内机净尺寸",
            field: "内机净尺寸",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "外机净尺寸",
            name: "外机净尺寸",
            field: "外机净尺寸",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "内机包装尺寸",
            name: "内机包装尺寸",
            field: "内机包装尺寸",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "外机包装尺寸",
            name: "外机包装尺寸",
            field: "外机包装尺寸",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "连接管液管规格",
            name: "连接管液管规格",
            field: "连接管液管规格",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "连接管气管规格",
            name: "连接管气管规格",
            field: "连接管气管规格",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "连接管最长配管",
            name: "连接管最长配管",
            field: "连接管最长配管",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "连接管追加冷媒量",
            name: "连接管追加冷媒量",
            field: "连接管追加冷媒量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "截止阀加大液管规格",
            name: "截止阀加大液管规格",
            field: "截止阀加大液管规格",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "截止阀加大气管规格",
            name: "截止阀加大气管规格",
            field: "截止阀加大气管规格",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "截止阀加大最长配管",
            name: "截止阀加大最长配管",
            field: "截止阀加大最长配管",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "截止阀加追加冷媒量",
            name: "截止阀加追加冷媒量",
            field: "截止阀加追加冷媒量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "最大落差",
            name: "最大落差",
            field: "最大落差",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "连接方式",
            name: "连接方式",
            field: "连接方式",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "控制方式",
            name: "控制方式",
            field: "控制方式",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "凝水管管径",
            name: "凝水管管径",
            field: "凝水管管径",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "是否需要能效认证",
            name: "是否需要能效认证",
            field: "是否需要能效认证",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "能效比BTUW",
            name: "能效比BTUW",
            field: "能效比BTUW",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "能效执行标准",
            name: "能效执行标准",
            field: "能效执行标准",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "产品执行标准",
            name: "产品执行标准",
            field: "产品执行标准",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "产品类型",
            name: "产品类型",
            field: "产品类型",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "认证",
            name: "认证",
            field: "认证",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "单冷热泵",
            name: "单冷热泵",
            field: "单冷热泵",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "机组分类",
            name: "机组分类",
            field: "机组分类",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "面板风口的尺寸",
            name: "面板风口的尺寸",
            field: "面板风口的尺寸",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "成品内机物料编码",
            name: "成品内机物料编码",
            field: "成品内机物料编码",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "成品外机物料编码",
            name: "成品外机物料编码",
            field: "成品外机物料编码",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "T3制冷量",
            name: "T3制冷量",
            field: "T3制冷量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "T3制冷电流",
            name: "T3制冷电流",
            field: "T3制冷电流",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "T3制冷功率",
            name: "T3制冷功率",
            field: "T3制冷功率",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "T3能效比EER",
            name: "T3能效比EER",
            field: "T3能效比EER",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "室内机电源",
            name: "室内机电源",
            field: "室内机电源",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "整机年耗电量",
            name: "整机年耗电量",
            field: "整机年耗电量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "能力保",
            name: "能力保",
            field: "能力保",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "能效比",
            name: "能效比",
            field: "能效比",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "定频变频",
            name: "定频变频",
            field: "定频变频",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "单位",
            name: "单位",
            field: "单位",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "工况",
            name: "工况",
            field: "工况",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "整机物料编码",
            name: "整机物料编码",
            field: "整机物料编码",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }]

    $scope.clearinformation = function () {
        $scope.data = {};
        $scope.data.currItem = {};
    };
    $scope.clearinformation();


    $scope.initData();

}

function pro_item_param_bp($scope, $location, $rootScope, $modal, $timeout, BasemanService, notify, $state, localeStorageService, FormValidatorService) {
    //设置当前对象名及主键名
    $scope.objconf = {
        classid: "pro_item_param_bp",
        key: "id",
        classids: "pro_item_param_bps",
        sqlWhereBlockID:"sqlWhereBlock6",
        hasStats:false,
        //SqlWhere:"1=1", 该条不存在就不要赋值
    }
    //继承基类方法
    pro_item_param_bp = HczyCommon.extend(pro_item_param_bp, ctrl_view_public);
    pro_item_param_bp.__super__.constructor.apply(this, [$rootScope, $scope, $location, $modal,
        $timeout, BasemanService, notify, $state, localeStorageService, FormValidatorService]);

    $scope.viewColumns = [
        {
            id: "id",
            name: "#",
            field: "id",
            behavior: "select",
            cssClass: "cell-selection",
            width: 40,
            cannotTriggerInsert: true,
            resizable: false,
            selectable: false,
            focusable: false
        }, {
            id: "整机型号",
            name: "整机型号",
            field: "整机型号",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "产品型号",
            name: "产品型号",
            field: "产品型号",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "室内机组型号",
            name: "室内机组型号",
            field: "室内机组型号",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "匹配外机型号",
            name: "匹配外机型号",
            field: "匹配外机型号",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "额定电压相数",
            name: "额定电压相数",
            field: "额定电压相数",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "额定频率",
            name: "额定频率",
            field: "额定频率",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷量",
            name: "制冷量",
            field: "制冷量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制热量",
            name: "制热量",
            field: "制热量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷电流",
            name: "制冷电流",
            field: "制冷电流",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制热电流",
            name: "制热电流",
            field: "制热电流",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷消耗功率",
            name: "制冷消耗功率",
            field: "制冷消耗功率",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制热消耗功率",
            name: "制热消耗功率",
            field: "制热消耗功率",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "最大电流",
            name: "最大电流",
            field: "最大电流",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "最大功率",
            name: "最大功率",
            field: "最大功率",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "换热器侧最大工作压力",
            name: "换热器侧最大工作压力",
            field: "换热器侧最大工作压力",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "吸气侧最大工作压力",
            name: "吸气侧最大工作压力",
            field: "吸气侧最大工作压力",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "排气侧最大工作压力",
            name: "排气侧最大工作压力",
            field: "排气侧最大工作压力",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷剂名称",
            name: "制冷剂名称",
            field: "制冷剂名称",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷剂注入量",
            name: "制冷剂注入量",
            field: "制冷剂注入量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "风量",
            name: "风量",
            field: "风量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "静压",
            name: "静压",
            field: "静压",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "内机噪声",
            name: "内机噪声",
            field: "内机噪声",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "外机噪声",
            name: "外机噪声",
            field: "外机噪声",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "内机净重",
            name: "内机净重",
            field: "内机净重",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "外机净重",
            name: "外机净重",
            field: "外机净重",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "内机毛重",
            name: "内机毛重",
            field: "内机毛重",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "外机毛重",
            name: "外机毛重",
            field: "外机毛重",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "内机机型代码",
            name: "内机机型代码",
            field: "内机机型代码",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "外机机型代码",
            name: "外机机型代码",
            field: "外机机型代码",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "电辅形式",
            name: "电辅形式",
            field: "电辅形式",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "电辅电压",
            name: "电辅电压",
            field: "电辅电压",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "电辅消耗功率",
            name: "电辅消耗功率",
            field: "电辅消耗功率",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "电辅电流",
            name: "电辅电流",
            field: "电辅电流",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "机组名称1",
            name: "机组名称1",
            field: "机组名称1",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "机组名称2",
            name: "机组名称2",
            field: "机组名称2",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "机组名称3",
            name: "机组名称3",
            field: "机组名称3",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "机组名称4",
            name: "机组名称4",
            field: "机组名称4",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "内机净机组尺寸",
            name: "内机净机组尺寸",
            field: "内机净机组尺寸",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "外机净机组尺寸",
            name: "外机净机组尺寸",
            field: "外机净机组尺寸",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "内机包装尺寸",
            name: "内机包装尺寸",
            field: "内机包装尺寸",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "外机包装尺寸",
            name: "外机包装尺寸",
            field: "外机包装尺寸",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "连接管液管规格",
            name: "连接管液管规格",
            field: "连接管液管规格",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "连接管气管规格",
            name: "连接管气管规格",
            field: "连接管气管规格",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "连接管最长配管",
            name: "连接管最长配管",
            field: "连接管最长配管",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "连接管追加冷媒量",
            name: "连接管追加冷媒量",
            field: "连接管追加冷媒量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "截止阀加大液管规格",
            name: "截止阀加大液管规格",
            field: "截止阀加大液管规格",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "截止阀加大气管规格",
            name: "截止阀加大气管规格",
            field: "截止阀加大气管规格",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "截止阀加大最长配管",
            name: "截止阀加大最长配管",
            field: "截止阀加大最长配管",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "截止阀加大追加冷媒量",
            name: "截止阀加大追加冷媒量",
            field: "截止阀加大追加冷媒量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "最大落差",
            name: "最大落差",
            field: "最大落差",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "连接方式",
            name: "连接方式",
            field: "连接方式",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "控制方式",
            name: "控制方式",
            field: "控制方式",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "凝水管管径",
            name: "凝水管管径",
            field: "凝水管管径",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "是否需要能效认证",
            name: "是否需要能效认证",
            field: "是否需要能效认证",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "能效比",
            name: "能效比",
            field: "能效比",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "能效执行标准",
            name: "能效执行标准",
            field: "能效执行标准",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "产品执行标准",
            name: "产品执行标准",
            field: "产品执行标准",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "产品类型",
            name: "产品类型",
            field: "产品类型",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "认证类型",
            name: "认证类型",
            field: "认证类型",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "单冷认证",
            name: "单冷认证",
            field: "单冷认证",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "机组分类",
            name: "机组分类",
            field: "机组分类",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "面板风口的尺寸",
            name: "面板风口的尺寸",
            field: "面板风口的尺寸",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "内机物料编码",
            name: "内机物料编码",
            field: "内机物料编码",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "外机物料编码",
            name: "外机物料编码",
            field: "外机物料编码",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "内机铭牌",
            name: "内机铭牌",
            field: "内机铭牌",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "外机铭牌",
            name: "外机铭牌",
            field: "外机铭牌",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "内机标牌",
            name: "内机标牌",
            field: "内机标牌",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "外机标牌",
            name: "外机标牌",
            field: "外机标牌",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "能效标识",
            name: "能效标识",
            field: "能效标识",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "最小制冷量",
            name: "最小制冷量",
            field: "最小制冷量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "最大制冷量",
            name: "最大制冷量",
            field: "最大制冷量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "最小制热量",
            name: "最小制热量",
            field: "最小制热量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "最大制热量",
            name: "最大制热量",
            field: "最大制热量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "最小制冷功率",
            name: "最小制冷功率",
            field: "最小制冷功率",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "最大制冷功率",
            name: "最大制冷功率",
            field: "最大制冷功率",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "最小制热功率",
            name: "最小制热功率",
            field: "最小制热功率",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "最大制热功率",
            name: "最大制热功率",
            field: "最大制热功率",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "最小制冷电流",
            name: "最小制冷电流",
            field: "最小制冷电流",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "最大制冷电流",
            name: "最大制冷电流",
            field: "最大制冷电流",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "最小制热电流",
            name: "最小制热电流",
            field: "最小制热电流",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "最大制热电流",
            name: "最大制热电流",
            field: "最大制热电流",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷功率2",
            name: "制冷功率2",
            field: "制冷功率2",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制热功率2",
            name: "制热功率2",
            field: "制热功率2",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷电流2",
            name: "制冷电流2",
            field: "制冷电流2",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制热电流2",
            name: "制热电流2",
            field: "制热电流2",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "外机扣减内电机P",
            name: "外机扣减内电机P",
            field: "外机扣减内电机P",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "室内机电压",
            name: "室内机电压",
            field: "室内机电压",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷SEER",
            name: "制冷SEER",
            field: "制冷SEER",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制热SCOP",
            name: "制热SCOP",
            field: "制热SCOP",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷耗电量",
            name: "制冷耗电量",
            field: "制冷耗电量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制热耗电量",
            name: "制热耗电量",
            field: "制热耗电量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "设计制冷量",
            name: "设计制冷量",
            field: "设计制冷量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "设计制热量",
            name: "设计制热量",
            field: "设计制热量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "内机声功率噪声",
            name: "内机声功率噪声",
            field: "内机声功率噪声",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "外机声功率噪声",
            name: "外机声功率噪声",
            field: "外机声功率噪声",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "产品类别",
            name: "产品类别",
            field: "产品类别",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "工况",
            name: "工况",
            field: "工况",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "定频变频",
            name: "定频变频",
            field: "定频变频",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "整机物料编码",
            name: "整机物料编码",
            field: "整机物料编码",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }]

    $scope.clearinformation = function () {
        $scope.data = {};
        $scope.data.currItem = {};
    };
    $scope.clearinformation();


    $scope.initData();

}

function pro_item_param_dln($scope, $location, $rootScope, $modal, $timeout, BasemanService, notify, $state, localeStorageService, FormValidatorService) {
    //设置当前对象名及主键名
    $scope.objconf = {
        classid: "pro_item_param_dln",
        key: "id",
        classids: "pro_item_param_dlns",
        sqlWhereBlockID:"sqlWhereBlock7",
        hasStats:false,
        //SqlWhere:"1=1", 该条不存在就不要赋值
    }
    //继承基类方法
    pro_item_param_dln = HczyCommon.extend(pro_item_param_dln, ctrl_view_public);
    pro_item_param_dln.__super__.constructor.apply(this, [$rootScope, $scope, $location, $modal,
        $timeout, BasemanService, notify, $state, localeStorageService, FormValidatorService]);

    $scope.viewColumns = [
        {
            id: "id",
            name: "#",
            field: "id",
            behavior: "select",
            cssClass: "cell-selection",
            width: 40,
            cannotTriggerInsert: true,
            resizable: false,
            selectable: false,
            focusable: false
        }, {
            id: "整机型号",
            name: "整机型号",
            field: "整机型号",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "产品型号",
            name: "产品型号",
            field: "产品型号",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "防触电保护类别",
            name: "防触电保护类别",
            field: "防触电保护类别",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "额定电压相数",
            name: "额定电压相数",
            field: "额定电压相数",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷量",
            name: "制冷量",
            field: "制冷量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制热量",
            name: "制热量",
            field: "制热量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "电机输入功率",
            name: "电机输入功率",
            field: "电机输入功率",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "功电加热率",
            name: "功电加热率",
            field: "功电加热率",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "电加热形式",
            name: "电加热形式",
            field: "电加热形式",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "内机风量",
            name: "内机风量",
            field: "内机风量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "内机静压",
            name: "内机静压",
            field: "内机静压",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "内机噪声",
            name: "内机噪声",
            field: "内机噪声",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "最大工作压力",
            name: "最大工作压力",
            field: "最大工作压力",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "内机净重",
            name: "内机净重",
            field: "内机净重",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "内机毛重",
            name: "内机毛重",
            field: "内机毛重",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "机型代码",
            name: "机型代码",
            field: "机型代码",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "机组名称1",
            name: "机组名称1",
            field: "机组名称1",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "机组名称2",
            name: "机组名称2",
            field: "机组名称2",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "机组名称3",
            name: "机组名称3",
            field: "机组名称3",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "内机净尺寸",
            name: "内机净尺寸",
            field: "内机净尺寸",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "内机包装尺寸",
            name: "内机包装尺寸",
            field: "内机包装尺寸",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "吊装尺寸",
            name: "吊装尺寸",
            field: "吊装尺寸",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "连接管液管规格",
            name: "连接管液管规格",
            field: "连接管液管规格",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "连接管气管规格",
            name: "连接管气管规格",
            field: "连接管气管规格",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "控制方式",
            name: "控制方式",
            field: "控制方式",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "能效标识",
            name: "能效标识",
            field: "能效标识",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "电源线规格",
            name: "电源线规格",
            field: "电源线规格",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "认证类型",
            name: "认证类型",
            field: "认证类型",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "热泵单冷",
            name: "热泵单冷",
            field: "热泵单冷",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "产品执行标准",
            name: "产品执行标准",
            field: "产品执行标准",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "成品内机物料编码",
            name: "成品内机物料编码",
            field: "成品内机物料编码",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "内机堆码层数",
            name: "内机堆码层数",
            field: "内机堆码层数",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "冷凝水水管管径",
            name: "冷凝水水管管径",
            field: "冷凝水水管管径",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷剂名称",
            name: "制冷剂名称",
            field: "制冷剂名称",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "产品类型",
            name: "产品类型",
            field: "产品类型",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "机组分类",
            name: "机组分类",
            field: "机组分类",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }]

    $scope.clearinformation = function () {
        $scope.data = {};
        $scope.data.currItem = {};
    };
    $scope.clearinformation();


    $scope.initData();

}

function pro_item_param_dlw($scope, $location, $rootScope, $modal, $timeout, BasemanService, notify, $state, localeStorageService, FormValidatorService) {
    //设置当前对象名及主键名
    $scope.objconf = {
        classid: "pro_item_param_dlw",
        key: "id",
        classids: "pro_item_param_dlws",
        sqlWhereBlockID:"sqlWhereBlock8",
        hasStats:false,
        //SqlWhere:"1=1", 该条不存在就不要赋值
    }
    //继承基类方法
    pro_item_param_dlw = HczyCommon.extend(pro_item_param_dlw, ctrl_view_public);
    pro_item_param_dlw.__super__.constructor.apply(this, [$rootScope, $scope, $location, $modal,
        $timeout, BasemanService, notify, $state, localeStorageService, FormValidatorService]);

    $scope.viewColumns = [
        {
            id: "id",
            name: "#",
            field: "id",
            behavior: "select",
            cssClass: "cell-selection",
            width: 40,
            cannotTriggerInsert: true,
            resizable: false,
            selectable: false,
            focusable: false
        }, {
            id: "整机型号",
            name: "整机型号",
            field: "整机型号",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "室外机组型号",
            name: "室外机组型号",
            field: "室外机组型号",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "室内机组型号",
            name: "室内机组型号",
            field: "室内机组型号",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "防触电保护类别",
            name: "防触电保护类别",
            field: "防触电保护类别",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "额定电压相数",
            name: "额定电压相数",
            field: "额定电压相数",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷量",
            name: "制冷量",
            field: "制冷量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制热量",
            name: "制热量",
            field: "制热量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷电流",
            name: "制冷电流",
            field: "制冷电流",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制热电流",
            name: "制热电流",
            field: "制热电流",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷消耗功率",
            name: "制冷消耗功率",
            field: "制冷消耗功率",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制热消耗功率",
            name: "制热消耗功率",
            field: "制热消耗功率",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "最大电流",
            name: "最大电流",
            field: "最大电流",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "最大功率",
            name: "最大功率",
            field: "最大功率",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "换热器侧最大工作压力",
            name: "换热器侧最大工作压力",
            field: "换热器侧最大工作压力",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "吸气侧最大工作压力",
            name: "吸气侧最大工作压力",
            field: "吸气侧最大工作压力",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "排气侧最大工作压力",
            name: "排气侧最大工作压力",
            field: "排气侧最大工作压力",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "制冷剂名称",
            name: "制冷剂名称",
            field: "制冷剂名称",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "注入量",
            name: "注入量",
            field: "注入量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "噪音",
            name: "噪音",
            field: "噪音",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "净重",
            name: "净重",
            field: "净重",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "毛重",
            name: "毛重",
            field: "毛重",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "外机机型代码",
            name: "外机机型代码",
            field: "外机机型代码",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "防水等级",
            name: "防水等级",
            field: "防水等级",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "机组名称1",
            name: "机组名称1",
            field: "机组名称1",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "机组名称2",
            name: "机组名称2",
            field: "机组名称2",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "机组名称3",
            name: "机组名称3",
            field: "机组名称3",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "外机净尺寸",
            name: "外机净尺寸",
            field: "外机净尺寸",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "外机包装尺寸",
            name: "外机包装尺寸",
            field: "外机包装尺寸",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "连接管液管规格",
            name: "连接管液管规格",
            field: "连接管液管规格",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "连接管气管规格",
            name: "连接管气管规格",
            field: "连接管气管规格",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "连接管最长配管",
            name: "连接管最长配管",
            field: "连接管最长配管",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "连接管追加冷媒量",
            name: "连接管追加冷媒量",
            field: "连接管追加冷媒量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "加大规格液管规格",
            name: "加大规格液管规格",
            field: "加大规格液管规格",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "加大规格气管规格",
            name: "加大规格气管规格",
            field: "加大规格气管规格",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "加大规格最长配管",
            name: "加大规格最长配管",
            field: "加大规格最长配管",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "加大规格追加冷媒量",
            name: "加大规格追加冷媒量",
            field: "加大规格追加冷媒量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "最大落差",
            name: "最大落差",
            field: "最大落差",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "连接方式",
            name: "连接方式",
            field: "连接方式",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "控制方式",
            name: "控制方式",
            field: "控制方式",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "最多可连接室内机台数",
            name: "最多可连接室内机台数",
            field: "最多可连接室内机台数",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "认证类型",
            name: "认证类型",
            field: "认证类型",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "单冷热泵带电辅",
            name: "单冷热泵带电辅",
            field: "单冷热泵带电辅",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "机组分类",
            name: "机组分类",
            field: "机组分类",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "执行标准",
            name: "执行标准",
            field: "执行标准",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "成品外机物料编码",
            name: "成品外机物料编码",
            field: "成品外机物料编码",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "外机铭牌物料编码",
            name: "外机铭牌物料编码",
            field: "外机铭牌物料编码",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "外机标牌物料编码",
            name: "外机标牌物料编码",
            field: "外机标牌物料编码",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "能效标识物料编码",
            name: "能效标识物料编码",
            field: "能效标识物料编码",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "是否需要能效认证",
            name: "是否需要能效认证",
            field: "是否需要能效认证",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "能效比BTU",
            name: "能效比BTU",
            field: "能效比BTU",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "能效比WW",
            name: "能效比WW",
            field: "能效比WW",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "能效执行标准",
            name: "能效执行标准",
            field: "能效执行标准",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "产品类型执行标准",
            name: "产品类型执行标准",
            field: "产品类型执行标准",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "产品类型",
            name: "产品类型",
            field: "产品类型",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "冷媒控制方式",
            name: "冷媒控制方式",
            field: "冷媒控制方式",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "压缩机润滑油类型",
            name: "压缩机润滑油类型",
            field: "压缩机润滑油类型",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "压缩机润滑油加注量",
            name: "压缩机润滑油加注量",
            field: "压缩机润滑油加注量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "冷媒控制方式2",
            name: "冷媒控制方式2",
            field: "冷媒控制方式2",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "容量控制",
            name: "容量控制",
            field: "容量控制",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "风扇类型",
            name: "风扇类型",
            field: "风扇类型",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "风扇电机输出",
            name: "风扇电机输出",
            field: "风扇电机输出",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "风扇风量",
            name: "风扇风量",
            field: "风扇风量",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "SCOP",
            name: "SCOP",
            field: "SCOP",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "SEER",
            name: "SEER",
            field: "SEER",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }, {
            id: "机组类型",
            name: "机组类型",
            field: "机组类型",
            width: 100,
            editor: Slick.Editors.ReadonlyText,
        }]

    $scope.clearinformation = function () {
        $scope.data = {};
        $scope.data.currItem = {};
    };
    $scope.clearinformation();


    $scope.initData();

}


promanControllers
    .controller('pro_item_param_fp', pro_item_param_fp)
    .controller('pro_item_param_kq', pro_item_param_kq)
    .controller('pro_item_param_sj', pro_item_param_sj)
    .controller('pro_item_param_thj', pro_item_param_thj)
    .controller('pro_item_param_t', pro_item_param_t)
    .controller('pro_item_param_bp', pro_item_param_bp)
    .controller('pro_item_param_dln', pro_item_param_dln)
    .controller('pro_item_param_dlw', pro_item_param_dlw)






